### ISSUE TITLE
Can I know please why?

### ISSUE THREAD

**Issue by mwlik** [DeRuina/philosophers#1]
PHILO_MAX is set to 300, even so its specified not to test with more than 200 (in the correction sheet and in you blog)?

**Comment by DeRuina** [comment]
I just wanted to show that it works even with more, there is no specific
reason. You van change it to 200 if you want

בתאריך יום ד׳, 31 בינו׳ 2024, 11:57, מאת Malik Mouhiidine ‏<
***@***.***>:

**Comment by mwlik** [comment]
alright, am gonna proceed to closing this issue.

**Comment by DeRuina** [comment]
Ok, thanks.

בתאריך יום ד׳, 31 בינו׳ 2024, 13:06, מאת Malik Mouhiidine ‏<
***@***.***>:
